export const BIOME_NAME_OVERRIDES: Record<string, string> = {
  "minecraft:stone_beach": "Stony Shore",
  "minecraft:cold_beach": "Snowy Beach",
  "minecraft:forest_hills": "Wooded Hills",
  "minecraft:birch_forest_mutated": "Old Growth Birch Forest",
  "minecraft:birch_forest_hills_mutated": "Tall Birch Hills",
  "minecraft:roofed_forest": "Dark Forest",
  "minecraft:roofed_forest_mutated": "Dark Forest Hills",
  "minecraft:jungle_mutated": "Modified Jungle",
  "minecraft:jungle_edge": "Sparse Jungle",
  "minecraft:jungle_edge_mutated": "Modified Jungle Edge",
  "minecraft:taiga_mutated": "Taiga Mountains",
  "minecraft:cold_taiga": "Snowy Taiga",
  "minecraft:cold_taiga_hills": "Snowy Taiga Hills",
  "minecraft:cold_taiga_mutated": "Snowy Taiga Mountains",
  "minecraft:mega_taiga": "Old Growth Pine Taiga",
  "minecraft:mega_taiga_hills": "Giant Tree Taiga Hills",
  "minecraft:redwood_taiga_mutated": "Old Growth Spruce Taiga",
  "minecraft:redwood_taiga_hills_mutated": "Giant Spruce Taiga Hills",
  "minecraft:mushroom_island": "Mushroom Fields",
  "minecraft:mushroom_island_shore": "Mushroom Field Shore",
  "minecraft:swampland": "Swamp",
  "minecraft:swampland_mutated": "Swamp Hills",
  "minecraft:savanna_mutated": "Windswept Savannah",
  "minecraft:savanna_plateau_mutated": "Shattered Savannah Plateau",
  "minecraft:desert_mutated": "Desert Lakes",
  "minecraft:ice_plains": "Snowy Plains",
  "minecraft:ice_mountains": "Snowy Mountains",
  "minecraft:ice_plains_spikes": "Ice Spikes",
  "minecraft:extreme_hills": "Windswept Hills",
  "minecraft:extreme_hills_plus_trees": "Windswept Forest",
  "minecraft:extreme_hills_mutated": "Windswept Gravelly Hills",
  "minecraft:extreme_hills_plus_trees_mutated": "Gravelly Mountains+",
  "minecraft:extreme_hills_edge": "Mountain Edge",
  "minecraft:mesa": "Badlands",
  "minecraft:mesa_plateau": "Badlands Plateau",
  "minecraft:mesa_plateau_mutated": "Modified Badlands Plateau",
  "minecraft:mesa_plateau_stone": "Wooded Badlands",
  "minecraft:mesa_plateau_stone_mutated": "Modified Wooded Badlands Plateau",
  "minecraft:mesa_bryce": "Eroded Badlands",
  "minecraft:hell": "Nether Wastes",
  "minecraft:soulsand_valley": "Soul Sand Valley",
};
